Repository MLH-Fellowship/twitstat, pull requests merged in 2020-10, with the labels that each got.

#14 Twitter Module
  .idea/misc.xml
  .idea/twitstat.iml
  apps/tweets.py
  requirements/base.txt
Labels: api, backend, new-feature

#12 Update documentation
  README.rst
  docs/source/about.rst
  docs/source/contributors.rst
  docs/source/future.rst
  docs/source/index.rst
  docs/source/nlp.rst
  docs/source/resources.rst
  docs/source/scrape.rst
Labels: documentation, low-priority

#19 Add bare-bones website
  .idea/misc.xml
  .idea/twitstat.iml
  website/css/bootstrap.min.css
  website/css/fontAwesome.css
  website/css/fonts/flexslider-icon.eot
  website/css/fonts/flexslider-icon.svg
  website/css/fonts/flexslider-icon.ttf
  website/css/fonts/flexslider-icon.woff
  website/css/hero-slider.css
  website/css/owl-carousel.css
  website/css/templatemo-main.css
  website/fonts/FontAwesome.otf
  website/fonts/fontawesome-webfont.eot
  website/fonts/fontawesome-webfont.svg
  website/fonts/fontawesome-webfont.ttf
  website/fonts/fontawesome-webfont.woff
  website/fonts/fontawesome-webfont.woff2
  website/fonts/glyphicons-halflings-regular.eot
  website/fonts/glyphicons-halflings-regular.svg
  website/fonts/glyphicons-halflings-regular.ttf
  website/fonts/glyphicons-halflings-regular.woff
  website/img/close.png
  website/img/loading.gif
  website/img/next.png
  website/img/prev.png
  website/img/twitter-bird-on-blue-background.png
  website/index.html
  website/js/main.js
  website/js/plugins.js
  website/js/vendor/bootstrap.min.js
  website/js/vendor/jquery-1.11.2.min.js
  website/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js
  website/js/vendor/npm.js
  website/prepros-6.config
Labels: frontend, high-priority, ui-enhancement

#20 Built the json output to be integrated with the HTML
  app.py
  apps/clean_data.py
  apps/process_data.py
  apps/tweets.py
  requirements/base.txt
Labels: backend
